apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    # kubernetes.io/change-cause: "this is default version"
      kubernetes.io/change-cause: "this is for nginx 1.21.3"
spec:
  replicas: 3
  selector:
    matchLabels:
      team: devops
  template:
    metadata: 
      name: nginx-pod
      labels:
        team: devops
        app: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.21.3
        ports:
        - containerPort: 80 